matrix:
    include:
        - os: linux
          language: android
          sudo: false
          android:
            components:
              - build-tools-23.0.1
              - android-23
              - extra-google-m2repository
              - extra-android-m2repository
          env: TERM=dumb
        - os: osx
          language: objective-c
          osx_image: xcode7.3

install: scripts/install.sh
script: scripts/ci.sh